---
sudo: required

dist: trusty

group: deprecated-2017Q3

language: python

python: 3.6

services:
  - docker

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
  - pip install --upgrade "pipenv==2018.10.13"

install:
  - yes | pipenv install --dev --deploy

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
