---
language: python

sudo: required

services:
  - docker

install:
  - pip install pipenv
  - pipenv install --deploy

script:
  - pipenv run molecule test --destroy never

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
