---
- name: Ensure UFW is installed
  apt: name=ufw state=present

- name: Allow specified IPs through the firewall to the SSH port
  ufw: rule=allow from_ip="{{ item }}" to_port=22
  with_items: "{{ secure_device_ssh_allowed_ips }}"

- name: Ensure some ports are open to everyone
  ufw: rule=allow to_port="{{ item }}"
  with_items: "{{ secure_device_everyone_ports }}"

- name: Ensure the firewall is enabled, and the default policy is deny
  ufw: state=enabled policy=deny
