---
- name: Ensure UFW is installed
  package: name=ufw state=present

- name: Allow specified IPs through the firewall to the SSH port
  ufw:
    rule: allow
    from_ip: "{{ item }}"
    port: 22
    proto: tcp
  with_items: "{{ secure_device_ssh_allowed_ips }}"

- name: Ensure some ports are open to everyone
  ufw:
    rule: allow
    port: "{{ item.port | default(item) }}"
    proto: "{{ item.proto | default(omit) }}"
  with_items: "{{ secure_device_everyone_ports }}"

- name: Ensure the firewall is enabled, and the default policy is deny
  ufw: state=enabled policy=deny
