---
- name: Ensure logwatch is absent
  package: name=logwatch state=absent
  when: not secure_device_log_email

- name: Ensure logwatch is present
  package: name=logwatch state=present
  when: secure_device_log_email

- name: Ensure the logwatch config is present
  lineinfile:
    dest: '/etc/cron.daily/00logwatch'
    line: "/usr/sbin/logwatch --mailto {{ secure_device_log_email }} --detail high"
    regexp: '^/usr/sbin/logwatch '
  when: secure_device_log_email
