---
- name: Ensure logwatch is absent
  package:
    name: logwatch
    state: absent
  when: not secure_device_log_email

- name: Uninstall logwatch
  when: secure_device_log_email | default(false)
  block:
    - name: Ensure logwatch is present
      package:
        name: logwatch
        state: present

    - name: Ensure the logwatch configuration is set
      lineinfile:
        path: /usr/share/logwatch/default.conf/logwatch.conf
        line: "{{ item.key }} = {{ item.value }}"
        regexp: "^{{ item.key }} ="
      with_dict:
        Detail: High
        MailTo: "{{ secure_device_log_email }}"
