---
- name: Install unattended upgrade management
  when: secure_device_install_unattended_upgrades
  block:
    - name: Ensure unattended upgrades is installed
      ansible.builtin.package:
        name: unattended-upgrades
        state: present

    - name: Ensure the periodic config is present
      ansible.builtin.copy:
        src: 10periodic
        dest: /etc/apt/apt.conf.d/10periodic
        mode: 0644

    - name: Ensure the unattended upgrade config is present
      ansible.builtin.copy:
        src: 20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        mode: 0644

    - name: Ensure the unattended upgrade config is present, part 2
      ansible.builtin.template:
        src: 50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        mode: 0644

- name: Install unattended upgrade management
  when: not secure_device_install_unattended_upgrades
  block:
    - name: Ensure unattended upgrades is not installed
      ansible.builtin.package:
        name: unattended-upgrades
        state: absent

    - name: Ensure periodic config is removed
      ansible.builtin.file:
        state: absent
        path: /etc/apt/apt.conf.d/10periodic

    - name: Ensure unattended upgrade config is removed
      ansible.builtin.file:
        state: absent
        path: /etc/apt/apt.conf.d/20auto-upgrades

    - name: Ensure unattended upgrade config is removed, part 2
      ansible.builtin.file:
        state: absent
        path: /etc/apt/apt.conf.d/50unattended-upgrades
