---
- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart chrony
  service:
    name: chrony
    state: restarted

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
